sonar.projectKey=meu-springboot
sonar.projectName=Grupo E - flowiaApi
sonar.host.url=https://sedimentologic-crescentlike-tijuana.ngrok-free.dev/
sonar.token=sqa_80d211278e16739e8db28391b49ead22c61d0b2e
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
